includes = ["exclude.toml"]

[default]
repository = "rclone:alist:/baidu/apps/bypy/dictionaries"
password-file = "/home/t/o/passwd.txt"
# Other options can be given here - note that opendal also support reading config from env
# files or AWS config dirs, see the opendal S3 docs for more information
# https://opendal.apache.org/docs/rust/opendal/services/struct.S3.html
# [repository.options]
# access_key_id = "003d8916a2e2ffb0000000002" # this can be ommited, when AWS config is used
# secret_access_key = "K003HyKFzUHJ5jQudkqxvxa2owbYSmM" # this can be ommited, when AWS config is used
# bucket = "codeberg"
# bucket_id = "2db8d941262a12ee926f0f1b"
# root = "/codeberg"

[default.backup]
label = "dictionaries"
sources = ["/d/sync/dictionaries", "/d/sync/dictionaries3", "/d/sync/small", "/d/pw/pm", "/d/pw/Roaming","/d/cache"]
